### ISSUE TITLE
UnsignedAddition simplification

### ISSUE THREAD

**Issue by wqweto** [cristianbuse/VBA-MemoryTools#1]
JFYI, here is popular and much shorter way to prevent overflows in pointer arithmetic in 32-bit VB6 which can be ported to 64-bit VBA easily I guess

```
Private Function UnsignedAdd(ByVal lUnsignedPtr As Long, ByVal lSignedOffset As Long) As Long
    '--- note: safely add *signed* offset to *unsigned* ptr for *unsigned* retval w/o overflow in LARGEADDRESSAWARE processes
    UnsignedAdd = ((lUnsignedPtr Xor &H80000000) + lSignedOffset) Xor &H80000000
End Function
```

But this is mostly not needed in client application code even for LARGEADDRESSAWARE 32-bit processes nowadays as a reliable technique to prevent pointer arithmetic overflows is to VirtualAlloc a 64KB sentinel chunk around 2GB boundary at application start up so that the boundary is never (rarely) crossed in normal pointer operations.

This same sentinel chunk fixes native `PropertyBag` as well which has troubles when internal storage crosses 2GB boundary.

**Comment by cristianbuse** [comment]
Hi Vladimir,

First of all, it's an honor to have you look over my code. I've immediately recognized your 'wqweto' user ID. I've previously looked and shared links to your [ModernSubclassingThunk](https://github.com/wqweto/ModernSubclassingThunk). I even started an email to you because I was wondering to what degree it was possible to achieve that for VBA7. Gave up as I don't have C++ or assembly knowledge and did not want to bother you. If you don't mind me asking with this occasion, is it feasible?

Before I actually reply to your comment, I want to share a way to make class initializers immutable (this repo is used for that). See [Private Class Initializer](https://codereview.stackexchange.com/questions/253233/private-vba-class-initializer-called-from-factory-2). I am wondering if it works in VB6 (which I don't have to test with). I would be grateful if you had a chance to look at and maybe even review.

As for your comment, I was aware of the bitwise operation to do Unsigned addition. I had 2 reasons to go with the ```If``` implementation:
 1. I wanted to be able to re-raise the overflow error (i.e. set the source to the method name). I did not want to put the whole method under ```On Error Resume Next``` or ```On Error GoTo...``` to achieve that because it would slow down the speed. I remember testing with millions of iterations to even see the difference. The way I did it only requires the error handling on one of the 4 cases
 2. I wasn't too good at working with bits. Hence the long explanation in code as I thought it would make it easier for the average VB users to understand what the method does.

Also, I've simply copy-pasted the method form an older repo of mine, [StringBuffer](https://github.com/cristianbuse/VBA-StringBuffer/blob/master/Code%20Modules/StringBuffer.cls)

In terms of compactness, your version is definitely better. In terms of readability, your version is also better but only for 'advanced' users.

I always suspected that the Unsigned addition is not needed especially if I am incrementing memory addresses with just a few bytes. Hence, I did not use it within the main functions as a second optional parameter but rather left it as a stand-alone method that a user can choose to use or not. Thank you for the explanation. I am wondering if I should use the addition in the private initializer that I've linked above. If you have the time to look over it, I suspect you would say 'NO'.

Finally, I would like to hear your thoughts on the ```Variant``` dereferencing method. It is something I discovered by pure luck a couple of months ago while working on the [WeakReference](https://github.com/cristianbuse/VBA-WeakReference) repo. Do you see any downsides to it? I found it very fast compared to just using ```RtlMoveMemory```.

**Comment by cristianbuse** [comment]
Yes, very easy to port to x64 bits:
```VBA
#If Win64 Then
Public Function UnsignedAdd(ByVal unsignedPtr As LongLong, ByVal signedOffset As LongLong) As LongLong
    UnsignedAdd = ((unsignedPtr Xor &H8000000000000000^) + signedOffset) Xor &H8000000000000000^
End Function
#Else
Public Function UnsignedAdd(ByVal unsignedPtr As Long, ByVal signedOffset As Long) As Long
    UnsignedAdd = ((unsignedPtr Xor &H80000000) + signedOffset) Xor &H80000000
End Function
#End If
```

I will update it and leave it in there just in case somebody needs it. I will include your comment above the method definition and link to your account. Hope you won't mind.

Again thanks for the code! Definitely more compact and faster.

Too bad you are so busy, I would have loved to hear your feedback on the Private Class Initializer that I've linked before.
