### ISSUE TITLE
?

### ISSUE THREAD

**Issue by beria23** [cristianbuse/VBA-MemoryTools#4]

**Comment by beria23** [comment]
I'm getting strange errors in MS Office 2010 in windows 10 ltsc. Is this normal or did I just install it wrong?

**Comment by cristianbuse** [comment]
@beria23 Hi,

You only need the ```LibMemory``` module.
In case you copy-pasted then make sure you exclude the ```Attribute VB_Name = "LibMemory"``` first line. Otherwise use the Zip or clone the repository.

If this is something else then please give me more details.

Thanks!

**Comment by beria23** [comment]
Thank you for replying and I apologize for English - it is not my native language.  I inserted a new module from libmemory.bas in the MVBfA window and named it libmemory. The same for DemoLibMemory. Running DemoMain and I see the Visual Basic for Application environment message - Compile Error:Variable not defined. That's the end of it...... How it looks like - https://mega.nz/file/2FNzURCT#xWK7qJUBAuVe0Lq_zy_jfNfIHuA-f0tjG6j-xpO7U8k
.........
My goal is to get fast methods for string and array operations, since the standard ones are horrible -.... Ideally, also sorting.  So far, (I've been studying VBA for a week and I'm horrified with how little functionality the language has) I was able to do only one procedure, but I'm not sure if I did it right and I'm not satisfied with the speed so far...
Option Explicit
Option Base 0
#If Win64 Then
 Public Declare PtrSafe Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" (Destination As Any, Source As Any, ByVal Length As LongPtr)
#Else
 Public Declare Sub CopyMemory Lib "kernel32" Alias "RtlMoveMemory" (Destination As Any,Source As Any, ByVal Length As Long)
#End If    
Public Sub SwapString(ByRef String1 As String, ByRef String2 As String)
#If Win64 Then
    Dim Save As LongPtr
#Else
    Dim Save As Long
#End If
    Save = StrPtr(String1)
    Call CopyMemory(ByVal VarPtr(String1), ByVal VarPtr(String2), 4)
    Call CopyMemory(ByVal VarPtr(String2), Save, 4)
End Sub

**Comment by cristianbuse** [comment]
@beria23 I can't view your link as that triggers my firewwall.

Anyway, it seems you copy pasted the code so I suggest you import it instead. Download the [Zip](https://github.com/cristianbuse/VBA-MemoryTools/archive/refs/heads/master.zip) and then right-click any of the existing modules and click 'Import File' then browse to the files from the Zip:  
![image](https://i.stack.imgur.com/CoYka.png)

After successfully importing the ```LibMemory``` module you can rewrite your code to:  
```VBA
Public Sub SwapString(ByRef String1 As String, ByRef String2 As String)
    #If Win64 Then
        Dim Save As LongLong
    #Else
        Dim Save As Long
    #End If
    Save = StrPtr(String1)
    MemLongPtr(VarPtr(String1)) = MemLongPtr(VarPtr(String2))
    MemLongPtr(VarPtr(String2)) = Save
End Sub
```

**Comment by beria23** [comment]
Used the new method, got exactly the same result and uploaded a screenshot to another exchanger, if MEGA is banned in your country because of censorship..... I'm probably dumb and I don't know something sacred about VBA, which I just started to learn....
https://drive.google.com/file/d/1TR_yMymHkxQTegif9x9AeLTMIISs9_O4/view?usp=sharing

How to insert a screenshot here on the forum, I have not found (

**Comment by beria23** [comment]
Your way of modifying my procedure WORKS!!! You are a genius...  A real VBA genius!
a1 = "-dimatryttytyttytrytrgfgfdytr-"
    a2 = "-durhfhfhfhfhfhfhfhfhfa2-"
    t = Timer
    For i = 1 To 100000
        SwapString1 a1, a2
    Next
    MsgBox Timer - t
    t = Timer
    For i = 1 To 100000
        SwapString2 a1, a2
    Next
    MsgBox Timer - t
My option is 0.3 seconds, your option is 0.05 seconds.....
And yes, the lags in my code are almost gone.
Still need to figure out how your code works to make the same fast basic procedures for string operations and other data types......

**Comment by cristianbuse** [comment]
@beria23 Thanks! Was able to view the picture this time.

The ```DemoClass``` has a special hidden attribute ```Attribute VB_PredeclaredId = True``` which is only visible in the text file. The only way to make it work is to import the module (not copy-paste code). Use the print screen in my previous comment to see how you insert a module from file and also make sure you download the Zip and extract the files or clone the repository in a local folder so that you import the correct files.

You can insert a screenshot using something like this: ```![alt text](http://url/to/img.png)``` where the url is a link to a web picture

**Comment by cristianbuse** [comment]
>Still need to figure out how your code works to make the same fast basic procedures for string operations and other data types......

The whole library is based around the fact that we can manipulate the VarType (first 2 bytes) in a Variant even with native code. This runs faster than the CopyMemory API but only in Win VBA7 - API is still faster in VBA6 and MAC.

What kind of String operations do you want to achieve? I ask because I might implement them directly in my repo if they are useful.

Thank you for the kind words!

**Comment by cristianbuse** [comment]
@beria23 

Just in case you missed my last comment, can you let me know what kind of String operations you are looking to implement? I would like to implement them if they are useful.

Also, here is a faster version of the swap, using less stack frames:  
```VBA
Public Sub SwapString(ByRef String1 As String, ByRef String2 As String)
    Static rm1 As REMOTE_MEMORY: If Not rm1.isInitialized Then InitRemoteMemory rm1
    Static rm2 As REMOTE_MEMORY: If Not rm2.isInitialized Then InitRemoteMemory rm2
    '
    rm1.memValue = VarPtr(String1)
    rm2.memValue = VarPtr(String2)
    '
    SwapPtrs rm1.remoteVT, rm2.remoteVT, rm1.memValue, rm2.memValue
End Sub

Private Function SwapPtrs(ByRef vt1 As Variant _
                        , ByRef vt2 As Variant _
                        , ByRef value1 As Variant _
                        , ByRef value2 As Variant)
    Dim vt As VbVarType
    Dim temp As Variant
    #If Win64 Then
        vt = vbCurrency
    #Else
        vt = vbLong
    #End If
    '
    vt1 = vt + VT_BYREF
    vt2 = vt1
    '
    temp = value1
    value1 = value2
    value2 = temp
End Function
```

**Comment by beria23** [comment]
Sorry for the delay in responding. I was out of town... ))))

I just sat down to study VBA and right now I have a very, very big problem with the performance of the complex legacy VBA code I'm rewriting.  I'm rewriting basic constructions and primitive functions for sorting, loops over arrays of strings and strings themselves, memory allocation (if anything I still don't know how to allocate memory for a string or one-dimensional archive without filling it unnecessarily)... and so on. 
In particular, the SwapString procedure was developed for an algorithm of sorting a very large array of strings, and it has already helped me greatly, speeding up the algorithm almost 10 times, what I'm very pleased with... )))
And here's a list of problems:
1. Getting the code of the string character in Asc(Mid(a4, i, 1)) works 3 times faster than MemInt(StrPtr(a4) + i * 2). I was VERY surprised by it. 
2. How to quickly fill a string with a certain character....... That is, like the FillChar procedure in Pascal (starting address, number of words,value)
3.  Allocate memory for a large dynamic string faster than a4=String(10000000, "A") works and without filling it unnecessarily, which is not used... In pascal it's getmem (p, size), where p is the pointer and size is the size in bytes of the dynamic memory fragment to be allocated.
Sorry to burden you with my problems....
ps: the question about dynamic virtual memory for very, very, very large arrays, which, if necessary, can be reset to disk, I don't even bring up anymore...

**Comment by cristianbuse** [comment]
Hi @beria23 

I appreciate it but there is no need to apologize. I was actually out of town myself for a few days.

## Problem 1 - Getting the code of the string character

I am not surprised that ```Asc(Mid(...))``` is faster because calling ```MemInt``` adds 2 stack frames to the call stack and moreover VBA is interpreted so much slower than whatever the library code is written in (most likely C or C++).

However, there is a way you can get better performance if you want to loop through the whole string and get the code for each character. You can read the string into an array of integers and then loop the array.

I just pushed a new ``` StringToIntegers``` method to the repository so you need to get the latest ```LibMemory``` module before you test the below:
```VBA
Option Explicit

Public Sub Main()
    Const iterations As Long = 10000
    Dim i As Long, j As Long
    Dim t As Double
    Dim s As String: s = Space$(1000)
    Dim a As Integer
    Dim codes() As Integer
    '
    t = Timer
    For i = 1 To iterations
        For j = 1 To Len(s)
            a = Asc(Mid$(s, j, 1))
        Next j
    Next i
    Debug.Print "Mid: " & Round(Timer - t, 3)
    '
    t = Timer
    codes = StringToIntegers(s, lowBound:=1)
    For i = 1 To iterations
        For j = 1 To Len(s)
            a = codes(j)
        Next j
    Next i
    Debug.Print "Mem: " & Round(Timer - t, 3)
End Sub
```

It works faster for strings longer than 10 characters and I get a 10x speed gain in the test above.

## Problem 2 - How to quickly fill a string with a certain character

You definitely already know about the ```String``` function which generates a new string filled with whatever character you want because you wrote it under the 3rd issue.

To write into a string, you can use the ```Mid``` statement (not the function) as the left side of the assignment. For example:  
```VBA
Sub TestFill()
    Dim buffer As String: buffer = Space$(10)
    '
    Mid$(buffer, 1, 5) = String$(5, "A")
    Mid$(buffer, 6, 5) = String$(5, "B")
    '
    Debug.Print buffer 'Prints: AAAAABBBBB
End Sub
```

I am not sure if this answers your problem. I was thinking that you might want a method that fills memory directly into an existing string without allocating memory with the ```String``` function. Maybe it could be achieved by copying memory in chunks that double in size with each iteration - could be a good strategy. However, I do not have the time to test this in the next few days and maybe the above example is already covering your needs. Please let me know your thoughts.

## Problem 3 - Allocate memory for a large dynamic string

I need a bit more info to understand why you want to generate a large dynamic string.

My first guess would be that you want to use it as a buffer. In this case I would use a strategy to increase the buffer as needed. See my [StringBuffer](https://github.com/cristianbuse/VBA-StringBuffer) repository and in particular look at the [EnsureCapacity](https://github.com/cristianbuse/VBA-StringBuffer/blob/master/Code%20Modules/StringBuffer.cls#L125) method. It works quite well for buffering.

**Comment by beria23** [comment]
Thank you very much for the answer and your work, as always, is amazing.... But I have a question about StringToIntegers....
I decided to reach the speed limit of the loop and made a full string interrator procedure in Pascal (Free Pascal)
It looks like this....

type
  TStringProcedure = procedure(i: smallint); 


 procedure RunProcStr2(Addr: Pointer; Proc: TStringProcedure); stdcall;
  var
    i: longword;
    Len: longword;
  begin
    Len := longword((Addr - 4)^);
    If Len = 0 then exit;
    Len := Len div 2 - 1;
    for i := 0 to Len do Proc(smallint((Addr + i shl 1)^));
  end;             

In VBA it starts as:
Sub MyProc(ByVal Ind As Integer)
    a = Ind
End Sub

 RunProcStr2 StrPtr(s), AddressOf MyProc

It works fine by going through the entire string and calling MyProc for each two-byte character....
Then I ran tests comparing it to your version on strings of different sizes. I got it right...

Len : 100000000
Byte : 200000000
Memory : 1,23
Pascal : 3,846
Len : 100000
Byte : 200000
Memory: 0.031
Pascal : 0,004

Next, questions..... How does your procedure work at all, that it produces such a huge speed? Yes, I know I'm a fool. )
My guess is that it lets you address a string as an array (arrays in VBA are fast) by overlaying their addresses in memory on top of each other. But here's the question, what will happen if the memory manager independently frees the memory of both variables (string and array) .....That is, a guaranteed crash of the entire memory manager of the application....

Why your procedure strongly wins on large strings and loses on small strings, where in general the speed increases strictly linearly with the size of the string..... I don't have any answer here...

**Comment by cristianbuse** [comment]
Hi @beria23

Thanks again for the kind words!

The ```StringToIntegers``` method copies all the bytes from the String into an array of Integers.
The copy happens in the ```RemoteAssign``` method on the ```targetVariable = newValue``` line. When assigning an array variable to another array variable, a copy is made by default, in VBA.

So, there is no danger of crashing the application as there is no memory overlap.

Well, actually there is a memory overlap but only within the scope of ```RemoteAssign```after the ```targetVariable = newValue``` line is executed and before the very next line ```remoteVT = vbEmpty``` is executed. For a crash to happen you would have to stop the code on purpose on the ```remoteVT = vbEmpty``` line and click the IDE Stop button or execute ```End``` in the Immediate window. Highly unlikely there is ever going to be a crash.

Actually, a second copy of the array happens when you assign the result of ```StringToIntegers``` to the local array where you do the iteration. Since the overhead is 2 array copies and 2 stack frames (```StringToIntegers``` and ```RemoteAssign```) then for small texts it's faster to iterate using ```Mid``` or your Pascal solution. However, for larger strings the overhead is negligible compared to the gains.

If I were to rewrite the ```StringToIntegers``` function as a ```Sub``` that returns the array as a second ```ByRef``` parameter, then I could get rid of the second copy. I don't think that would add much value.

Moreover, I could write the method in such a way to make no copy and return the array of integers by reference using something similar with the ```GetArrayByRef``` method. There would be no danger of freeing the memory twice because the returning ```Variant``` would have the ```VT_BYREF``` flag set. However, iterating over an array of integers wrapped in a ```Variant``` is around 4 times slower than making a copy and iterating over an array of integers.

Let me know if you still have questions and also please don't forget to reply to problem 2 and 3 in my previous comment. Thanks!

BTW, for a String of length 100000 I get either 0.004 or 0.000 for a single run while I see you got 0.031. Did you average the timing for a specific number of iterations? For example if I average for 1000 or 10000 iterations then I get a constant 0.001 seconds.
