### ISSUE TITLE
CopyMemory tests

### ISSUE THREAD

**Issue by dragokas** [cristianbuse/VBA-MemoryTools#5]
Some criticism about the tests.
CopyMemory is surely very slow if you use it to copy 1-8 byte blocks, because it includes lot of security checks.
More effective would be to use functions: GetMem1, GetMem2, GetMem4, GetMem8 from msvbvm60.dll (Visual Basic 6 runtime which is available in all Windows OS).
Example, assembled according to your test unit:
```
Public Declare Function GetMem1 Lib "msvbvm60.dll" (Src As Any, Dst As Any) As Long

Private Sub DemoMemByteSpeed()
    Dim x1 As Byte: x1 = 1
    Dim x2 As Byte: x2 = 2
    Dim i As Long
    Dim t As Double
    
    Const LOOPS As Long = 10000000
    
    t = Timer
    For i = 1 To LOOPS
        MemByte(VarPtr(x1)) = MemByte(VarPtr(x2))
    Next i
    Debug.Print "Copy <" & TypeName(x1) & "> By Ref " & Format$(LOOPS, "#,##0") _
        & " times in " & Round(Timer - t, 3) & " seconds"
    DoEvents
    
    t = Timer
    For i = 1 To LOOPS
        CopyMemory x1, x2, 1
    Next i
    Debug.Print "Copy <" & TypeName(x1) & "> By CopyMemory API " & Format$(LOOPS, "#,##0") _
        & " times in " & Round(Timer - t, 3) & " seconds"
    DoEvents
    
     t = Timer
    For i = 1 To LOOPS
        GetMem1 x2, x1
    Next i
    Debug.Print "Copy <" & TypeName(x1) & "> By GetMem1 API " & Format$(LOOPS, "#,##0") _
        & " times in " & Round(Timer - t, 3) & " seconds"
    DoEvents
End Sub
```

Output:
```
Copy <Byte> By Ref 10 000 000 times in 3,477 seconds
Copy <Byte> By CopyMemory API 10 000 000 times in 0,242 seconds
Copy <Byte> By GetMem1 API 10 000 000 times in 0,102 seconds
```

**Comment by cristianbuse** [comment]
Hi @dragokas ,

Thanks for running those tests!

```CopyMemory``` should be very fast, way faster than what I am doing. However, the issue is not about ```CopyMemory``` itself but rather the API calls on VBA7 which are slow. For more details see [this](https://codereview.stackexchange.com/questions/270258/evaluate-performance-of-dll-calls-from-vba) CR post which shows that even a random API call is slow compared to VBA6. The below image is taken from that post:  
**Time in seconds required for completion of 10<sup>9</sup> repetitions.**
![pic](https://raw.githubusercontent.com/pchemguy/SQLiteC-for-VBA/develop/Assets/Diagrams/VBA%20Performance.png)

So, the issue is not ```CopyMemory``` but rather calling DLL APIs.

So, msvbvm60.dll does not have the issue because it's not VBA7. So, your tests are surely correct. However, this does not help as everyone I work with uses VBA7 and none of them even have msvbvm60.dll. I haven't had msvbvm60.dll for the last 5 years on any of my machines.

With no access to msvbvm60.dll and a slow CopyMemory, I had to create this solution.

**Comment by dragokas** [comment]
It's surely not much sense to compare with VBA methods, because they're interpreted and results in lot of speed loss.

Ahh, I didn't touch VBA for years. You must be speaking about x64 bit msvbvm60.dll, and yeah, such one unfortunately does not exist.
Only 32-bit version is pre-installed. So, for general use in VBA, it's really not appropriate.

**Comment by cristianbuse** [comment]
Hi @dragokas ,

Managed to get my hands on an older version of Excel.

These are the results on Excel 2007 x32:

```
Copy <Byte> By Ref 10,000,000 times in 2.82 seconds
Copy <Byte> By CopyMemory API 10,000,000 times in 0.281 seconds
Copy <Byte> By GetMem1 API 10,000,000 times in 0.086 seconds
```
which agree with your results.

Now, these are the results on Excel 365 ver 2208 x64:
```
Copy <Byte> By Ref 10,000 times in 0.016 seconds
Copy <Byte> By CopyMemory API 10,000 times in 10.367 seconds
```
and: 
![image](https://user-images.githubusercontent.com/23198997/212765847-abeb53c4-c94a-4e45-9ee0-b0bc140d7f15.png)

For the x64 test, if I were to extrapolate the 10,000 loops to 10,000,000 to match the x32 test then I would have to wait almost 3 hours for CopyMemory to complete.
